---
name: Calculator Deployment
on: 
  push:
    branch-ignore: 
      -data
      -gh-pages
    tags: 
      -'**'
  pull_request:
    branch-ignore:
      -data
      -gh-pages
jobs:
  KivyCalc:
    runs-on: ubuntu-22.04.2
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: main
      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with: 
          repository_root: main
          workdir: .
          buildozer_version: stable
      - name: Upload artifacts
        uses: actions/upload-artifacts@v2
        with:
          name: package
          path: ${{ step.buildozer.outputs.filename }}
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: main
          ref: main # Branch name
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
          architecture: x64
      - name: push binary to data branch
        if: github.event_name=='push'
        run: python main/.ci/move_binary.py {{ step.buildozer.outputs.filename }} main data bin
...
